#!/bin/bash
#PBS -P CFP01-CF-060
#PBS -j oe
#PBS -k oed
#PBS -N neuron_activation
#PBS -q auto
#PBS -l select=1:ngpus=1
#PBS -l walltime=24:00:00

cd $PBS_O_WORKDIR;

image="/app1/common/singularity-img/hopper/pytorch/pytorch_2.3.0_cuda_12.4_ngc_24.04.sif"

module load singularity

# mkdir logs
LOG_DIR=./logs/neuron_activation
if [ ! -d "$LOG_DIR" ]; then
  mkdir -p "$LOG_DIR"
fi

singularity exec -e \
--env HF_HOME=/scratch/e1583535/cache \
--env HF_DATASETS_CACHE=/scratch/e1583535/cache/datasets \
$image bash << EOF > $LOG_DIR/stdout.$PBS_JOBID.log 2> $LOG_DIR/stderr.$PBS_JOBID.log

source /hpctmp/e1583535/virtualenvs/lsneuron/bin/activate

CUDA_VISIVLE_DEVICES=0 python activation.py \
-m /scratch/e1583535/llm/nus-olmo/para-only-7B-34B-checkpoints/step8290-unsharded-hf \
-l vi 
--data_prefix data/parallel-only-7B-34B/ckpt-34 \
# --max_tokens_to_use 100 

echo "Done"

EOF